boot:
  flash:
    enabled: false
    imagePath: /Users/deepankarsingh/Downloads/DietPi_RPi-ARMv8-Bullseye/DietPi_RPi-ARMv8-Bullseye.img
    diskPath: /dev/disk2
    writeBs: 10m
    trackIntervalInSeconds: 1
    defaultVolumeName: "DIETPI"
  cgroups:
    enabled: true
    configText: "cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory"
    configFile: "cmdline.txt"
  nodeDetails:
    enabled: true
    hostname: dietpihost
    password: dietpi@123
  wifi:
    enabled: true
    name: your-wifi-name
    password: your-wifi-password
  k3s:
    enabled: true
    disableStartAsServer: true
  copyFiles:
    enabled: false
    paths: 
      - provide-file-path-here.txt
  firstBootExecutables:
    enabled: true
    paths:
      - provide-executable-file-here.sh
  defaultDietPiConfigs:
    - "SURVEY_OPTED_IN=0"
    - "AUTO_SETUP_AUTOMATED=1"
    - "AUTO_SETUP_BROWSER_INDEX=0"
    - "AUTO_SETUP_HEADLESS=1"
    - "AUTO_SETUP_SWAPFILE_SIZE=0"
    - "AUTO_SETUP_SWAPFILE_SIZE=1"
    - "AUTO_SETUP_SWAPFILE_LOCATION=/var/swap"
    - "AUTO_UNMASK_LOGIND=0"